# ── Perfil personalizado ──────────────────────────────────────────
# Cambia true/false según lo que necesites levantar
postgres:
  enabled: true
mongo:
  enabled: true
influxdb:
  enabled: true
minio:
  enabled: true
rabbitmq:
  enabled: true
emqx:
  enabled: true

# ── Microservicios e imágenes ─────────────────────────────────────
# imageSource: local  — usa la imagen del containerd del nodo (imagePullPolicy: Never)
# imageSource: remote — descarga desde DockerHub              (imagePullPolicy: IfNotPresent)
dataService:
  enabled: true
  imageSource: remote
  image: semillerocage/data-service
  tag: "1.5"

adminService:
  enabled: true
  imageSource: remote
  image: semillerocage/admin-service
  tag: "1.4"

frontendAdmin:
  enabled: true
  imageSource: local
  image: frontend-admin
  tag: latest
