apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: observability-low-priority
value: 100
globalDefault: false
preemptionPolicy: Never
description: "Prioridad baja para el stack de observabilidad"
