apiVersion: v1
kind: Secret
metadata:
  name: monitoring-credentials
  namespace: monitoring
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword }}
