apiVersion: v1
kind: Service
metadata:
  name: monitoring-alloy-otlp
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
spec:
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  type: ClusterIP
