apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: smart-campus
type: Opaque
stringData:
  # PostgreSQL
  POSTGRESQL_USER: {{ .Values.postgres.user }}
  POSTGRESQL_PASSWORD: {{ .Values.postgres.password }}
  POSTGRESQL_DB: {{ .Values.postgres.db }}
  # MongoDB
  MONGO_USERNAME: {{ .Values.mongo.username }}
  MONGO_PASSWORD: {{ .Values.mongo.password }}
  MONGO_DATABASE: {{ .Values.mongo.database }}
  # InfluxDB
  INFLUXDB_USER: {{ .Values.influxdb.user }}
  INFLUXDB_PASSWORD: {{ .Values.influxdb.password }}
  INFLUXDB_ORG: {{ .Values.influxdb.org }}
  INFLUXDB_BUCKET: {{ .Values.influxdb.bucket }}
  INFLUXDB_TOKEN: {{ .Values.influxdb.token }}
  # MinIO
  MINIO_ROOT_USER: {{ .Values.minio.rootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword }}
  # RabbitMQ
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password }}
